// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntxwzmsmffyxrtbkxuns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50eHd6bXNtZmZ5eHJ0Ymt4dW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTE2NTQsImV4cCI6MjA3MDY2NzY1NH0.8dSZy4-WuKt0ts9KYOGz0uOUejwBJMEXiEdsqtJHFdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});